name: Go

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  golangci:
    strategy:
      matrix:
        go: [1.16]
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          working-directory: ./go/cmd